package edu.taller.sisgea.mantenimientosgenerales.service.eventostransaccionmastercard;

import java.util.List;

import ob.commons.mantenimiento.service.IMantenibleService;
import edu.taller.sisgea.mantenimientosgenerales.model.EventosTransaccionMastercard;

public interface IEventosTransaccionMastercardService extends IMantenibleService<EventosTransaccionMastercard> {
	
	List<EventosTransaccionMastercard> buscarTodosEventosTransaccionMastercard();
	
	EventosTransaccionMastercard registrarEventosTransaccionMastercard(EventosTransaccionMastercard eventosTransaccionMastercard);
	
	EventosTransaccionMastercard actualizarEventosTransaccionMastercard(EventosTransaccionMastercard eventosTransaccionMastercard);
	
	void eliminarEventosTransaccionMastercard(EventosTransaccionMastercard eventosTransaccionMastercard);
}
