logging:
  config: "classpath:logback-spring.xml"
#El paquete ob.commons.mantenimiento.model contiene el objeto ParametroGeneralMantenimiento
mybatis:
  type-aliases-package: ob.unibanca.sicf.facturacion.model,
    ob.unibanca.sicf.mantenimientosgenerales.model,
    ob.commons.mantenimiento.model
  mapper-locations: classpath*:**/mapper/oracle/**/*Mapper.xml
server:
  servlet:
    context-path: /sicf/api
  port: 8080
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
  jackson:
    time-zone: EST
    date-format: dd/MM/yyyy
  profiles:
    active: dev-hllcc
    include: dev
  messages:
    encoding: UTF-8
